# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livesplit/bridge/v2/run.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'livesplit/bridge/v2/run.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from livesplit.bridge.v2 import common_pb2 as livesplit_dot_bridge_dot_v2_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlivesplit/bridge/v2/run.proto\x12\x13livesplit.bridge.v2\x1a livesplit/bridge/v2/common.proto\"\xf0\x02\n\x08RunState\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x14\n\x0crun_revision\x18\x02 \x01(\x04\x12\x11\n\tgame_name\x18\n \x01(\t\x12\x15\n\rcategory_name\x18\x0b \x01(\t\x12\x14\n\x0coffset_ticks\x18\x0c \x01(\x12\x12\x16\n\tfile_path\x18\r \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0blayout_path\x18\x0e \x01(\tH\x01\x88\x01\x01\x12\x32\n\x08metadata\x18\x14 \x01(\x0b\x32 .livesplit.bridge.v2.RunMetadata\x12\x13\n\x0b\x63omparisons\x18\x1e \x03(\t\x12\x32\n\x08segments\x18\x1f \x03(\x0b\x32 .livesplit.bridge.v2.SegmentInfo\x12-\n\tgame_icon\x18( \x01(\x0b\x32\x1a.livesplit.bridge.v2.ImageB\x0c\n\n_file_pathB\x0e\n\x0c_layout_path\"\xc9\x01\n\x0bSegmentInfo\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x38\n\x0b\x63omparisons\x18\n \x03(\x0b\x32#.livesplit.bridge.v2.ComparisonTime\x12\x39\n\x11\x62\x65st_segment_time\x18\x0b \x01(\x0b\x32\x1e.livesplit.bridge.v2.TimeValue\x12(\n\x04icon\x18\x0c \x01(\x0b\x32\x1a.livesplit.bridge.v2.Image\"L\n\x0e\x43omparisonTime\x12\x0c\n\x04name\x18\x01 \x01(\t\x12,\n\x04time\x18\x02 \x01(\x0b\x32\x1e.livesplit.bridge.v2.TimeValue\"\x92\x02\n\x0bRunMetadata\x12\x13\n\x06run_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rplatform_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bregion_name\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\ruses_emulator\x18\x04 \x01(\x08\x12\x42\n\tvariables\x18\n \x03(\x0b\x32/.livesplit.bridge.v2.RunMetadata.VariablesEntry\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\t\n\x07_run_idB\x10\n\x0e_platform_nameB\x0e\n\x0c_region_name\"G\n\x05Image\x12\x11\n\tmime_type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\rB\x1f\xaa\x02\x1cLiveSplit.Bridge.Protocol.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livesplit.bridge.v2.run_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034LiveSplit.Bridge.Protocol.V2'
  _globals['_RUNMETADATA_VARIABLESENTRY']._loaded_options = None
  _globals['_RUNMETADATA_VARIABLESENTRY']._serialized_options = b'8\001'
  _globals['_RUNSTATE']._serialized_start=89
  _globals['_RUNSTATE']._serialized_end=457
  _globals['_SEGMENTINFO']._serialized_start=460
  _globals['_SEGMENTINFO']._serialized_end=661
  _globals['_COMPARISONTIME']._serialized_start=663
  _globals['_COMPARISONTIME']._serialized_end=739
  _globals['_RUNMETADATA']._serialized_start=742
  _globals['_RUNMETADATA']._serialized_end=1016
  _globals['_RUNMETADATA_VARIABLESENTRY']._serialized_start=923
  _globals['_RUNMETADATA_VARIABLESENTRY']._serialized_end=971
  _globals['_IMAGE']._serialized_start=1018
  _globals['_IMAGE']._serialized_end=1089
# @@protoc_insertion_point(module_scope)
