# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livesplit/bridge/v1/bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'livesplit/bridge/v1/bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from livesplit.bridge.v1 import common_pb2 as livesplit_dot_bridge_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n livesplit/bridge/v1/bridge.proto\x12\x13livesplit.bridge.v1\x1a livesplit/bridge/v1/common.proto\"\xcb\x02\n\x07Request\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\x12\x34\n\x06\x61ttach\x18\n \x01(\x0b\x32\".livesplit.bridge.v1.AttachRequestH\x00\x12?\n\x0cget_snapshot\x18\x0b \x01(\x0b\x32\'.livesplit.bridge.v1.GetSnapshotRequestH\x00\x12\x45\n\x0ftimer_operation\x18\x0c \x01(\x0b\x32*.livesplit.bridge.v1.TimerOperationRequestH\x00\x12L\n\x13game_time_operation\x18\r \x01(\x0b\x32-.livesplit.bridge.v1.GameTimeOperationRequestH\x00\x42\x06\n\x04\x62ody\"\xa9\x02\n\x08Response\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\x12\x31\n\x05\x65rror\x18\n \x01(\x0b\x32 .livesplit.bridge.v1.BridgeErrorH\x00\x12\x35\n\x06\x61ttach\x18\x14 \x01(\x0b\x32#.livesplit.bridge.v1.AttachResponseH\x00\x12@\n\x0cget_snapshot\x18\x15 \x01(\x0b\x32(.livesplit.bridge.v1.GetSnapshotResponseH\x00\x12;\n\toperation\x18\x16 \x01(\x0b\x32&.livesplit.bridge.v1.OperationResponseH\x00\x42\x06\n\x04\x62ody\"\x0f\n\rAttachRequest\"Z\n\x0e\x41ttachResponse\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x34\n\x08snapshot\x18\x02 \x01(\x0b\x32\".livesplit.bridge.v1.TimerSnapshot\"\x14\n\x12GetSnapshotRequest\"K\n\x13GetSnapshotResponse\x12\x34\n\x08snapshot\x18\x01 \x01(\x0b\x32\".livesplit.bridge.v1.TimerSnapshot\"S\n\x15TimerOperationRequest\x12:\n\toperation\x18\x01 \x01(\x0e\x32\'.livesplit.bridge.v1.TimerOperationType\"w\n\x18GameTimeOperationRequest\x12=\n\toperation\x18\x01 \x01(\x0e\x32*.livesplit.bridge.v1.GameTimeOperationType\x12\x12\n\x05ticks\x18\x02 \x01(\x12H\x00\x88\x01\x01\x42\x08\n\x06_ticksB\x1f\xaa\x02\x1cLiveSplit.Bridge.Protocol.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livesplit.bridge.v1.bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034LiveSplit.Bridge.Protocol.V1'
  _globals['_REQUEST']._serialized_start=92
  _globals['_REQUEST']._serialized_end=423
  _globals['_RESPONSE']._serialized_start=426
  _globals['_RESPONSE']._serialized_end=723
  _globals['_ATTACHREQUEST']._serialized_start=725
  _globals['_ATTACHREQUEST']._serialized_end=740
  _globals['_ATTACHRESPONSE']._serialized_start=742
  _globals['_ATTACHRESPONSE']._serialized_end=832
  _globals['_GETSNAPSHOTREQUEST']._serialized_start=834
  _globals['_GETSNAPSHOTREQUEST']._serialized_end=854
  _globals['_GETSNAPSHOTRESPONSE']._serialized_start=856
  _globals['_GETSNAPSHOTRESPONSE']._serialized_end=931
  _globals['_TIMEROPERATIONREQUEST']._serialized_start=933
  _globals['_TIMEROPERATIONREQUEST']._serialized_end=1016
  _globals['_GAMETIMEOPERATIONREQUEST']._serialized_start=1018
  _globals['_GAMETIMEOPERATIONREQUEST']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
